### ISSUE TITLE
scenes not loading properly on exported project

### ISSUE THREAD

**Issue by dehboxturtle** [KoBeWi/Metroidvania-System#10]
Hello! Thanks for sharing this add-on, it is great! I was just curious if you've run into any issues in the past when exporting your project?

When I test things in Godot everything seems to work just fine, however when I tried exporting a windows build the game script seems to be failing to properly load scenes. I am using the game script from your sample project with some very minor tweaks. This is the first time I've made a game in Godot so apologies if I'm missing something obvious.

Here is a video showing what I mean (sorry it won't let me upload more than 10 MB) https://www.dropbox.com/scl/fi/ks8br1xs419k5mro25316/metsys_scene_loading_issue.mp4?rlkey=vwniia72m2sevlzq37ek08bci&dl=0

Happy to provide more info if it seems like it might be related to metsys or open a bug in Godot github if it seems like a more general issue.

**Comment by dehboxturtle** [comment]
Dug around a bit more and figured out how to export projects with debug enabled. It prints out this error
`WARNING: Map data file does not exist.`
I updated it to print the path that it is trying to find the file at and it says:
`Map data file does not exist. location: res://levels/MapData.txt`
Although it is definitely located there in the project so I'm not sure why it is failing to find it. I'll keep playing with it for now. Right now I suspect maybe some permissions issue or something?
<img width="121" alt="image" src="https://github.com/KoBeWi/Metroidvania-System/assets/58672268/ab3c1007-cae3-4b5a-bd70-3d5287335e2e">

**Comment by dehboxturtle** [comment]
Ah ok, figured it out! Apparently Godot does not export .txt files by default when you export your project. You have to manually specify it in the export settings.
<img width="447" alt="image" src="https://github.com/KoBeWi/Metroidvania-System/assets/58672268/a59bceff-d913-4175-ade2-bf70d6585e3c">

So I guess it ended up being a basic thing after all :P sorry for the noise! Hopefully this will help other new Godot users that are trying to use MetSys as well!

**Comment by Nordle** [comment]
@dehboxturtle thank you for spending the time to come back and document what you did. It also caught me out and a quick search saved me probably an hour or more of debugging ❤️
