### ISSUE TITLE
Map on reload of scene empty.

### ISSUE THREAD

**Issue by nyrrrr** [KoBeWi/Metroidvania-System#12]
Hi,

I used the code from your Game.gd, as well as the Code from the Minimap as well as the MapWindow.
My issue is, I load the Game scene from my main menu with
`get_tree().change_scene_to_file("res://Scenes/main.tscn")`
and all is fine. Mini Map is shown, current room is visible. Everything works.
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/7b76015d-68c2-4624-b878-c9df995c12cd)

Then I quit to the main menu again and there I press new game or continue, loading the scene again with `get_tree().change_scene_to_file("res://Scenes/main.tscn")` and suddenly the map is completely empty.
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/01b9a1d8-70c0-4fc5-a7d9-9558578824d9)

If I instead quit the entire application and start it again, the map is shown.
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/7b76015d-68c2-4624-b878-c9df995c12cd)

Is there some component or something I need to do to refresh the map data when loading the scene again?
Like do I have to somehow restart MetSys or something?

I could upload my current project somewhere, if you wanna check out the coding.

**Comment by KoBeWi** [comment]
When restarting scene, MetSys singleton holds the old player position and the first cell is not discovered.
I'll try to come up with a fix, in the meantime you can call `MetSys.last_player_position = Vector3i.MAX` when game starts.

**Comment by nyrrrr** [comment]
Thanks! That actually fixed it.

**Comment by KoBeWi** [comment]
Resolved by d33a3f7f8c72636bc25fd40c48797cfb3ed687fd
The commit adds a new method `reset_state()` that resets the variables for you.
