### ISSUE TITLE
Left panel too small to fit content

### ISSUE THREAD

**Issue by isaaccp** [KoBeWi/Metroidvania-System#14]
The left panel is too small to fit its content and requires scrolling. See image.

![image](https://github.com/KoBeWi/Metroidvania-System/assets/8712/f5bb95ef-4bd7-4e11-ab06-90f066a74a2f)

**Comment by KoBeWi** [comment]
As a workaround you can open MapEditor.tscn and disable horizontal scroll in the ScrollContainer.
I have it on my TODO list, I'll try to work on some update soon.

**Comment by isaaccp** [comment]
Worked great, thanks:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/8712/723276cb-cd72-4638-b077-7d1d043a9a13)

**Comment by KoBeWi** [comment]
Fixed by 0b3292d
