### ISSUE TITLE
Consider prefixing type names with MetSys prefix

### ISSUE THREAD

**Issue by isaaccp** [KoBeWi/Metroidvania-System#16]
I have been using MetSys but wanted to move to using a Resource for saving data.

I unfortunately created a SaveData.gd with class_name SaveData, which immediately caused Metsys to crash loop restarting Godot non-stop, due to the naming conflict with:
const SaveData = preload("res://addons/MetroidvaniaSystem/Scripts/SaveData.gd")
in MetroidvaniaSystem.gd.

It would be great if MetroidvaniaSystem used names like MetsysSaveData, MetsysSettings, etc, to prevent naming conflicts like this. Usually it's easy to figure those out, but the fact that it causes a reload loop makes it quite annoying.

**Comment by KoBeWi** [comment]
In 5a581cee07cc032ceb222110fc0820e9ce10ae36 I renamed Settings and SaveData to prevent common conflicts.
a60db99928513897c9bde93aef37d916138da8dd prevents restart loop. When singleton fails to load after restart, an error dialog appears instead.
