### ISSUE TITLE
Rooms layout is sometimes off the grid

### ISSUE THREAD

**Issue by nyrrrr** [KoBeWi/Metroidvania-System#18]
As you can see with the white room border line, the rooms' layout is not always the same. Which leads to problematic transitions (you can get stuck in a wall)

![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/4e13d139-e526-4a3a-8c9c-ef46bf6f1f36) vs 
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/3d4a16f7-e0ad-40a7-8b1f-aafe1de8a4cb)

(the one line is about 8 pixels lower than the other)

**Comment by KoBeWi** [comment]
The border lines are only helpers to show you the room's bounds. It's generally difficult to fit all tiles fully inside room, because it limits what tile sizes and resolutions you can use (especially with 16:9 ratio) and the borders may appear displaced depending on the layout.

I was thinking about adding a preview for neighboring scenes. It would make matching them easier. Maybe in some future version 🤔

**Comment by nyrrrr** [comment]
In the current setup, you run into problems like here 
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/76329a71-9f36-4c3f-aa9c-0405c056ed54)
 where when I leave the bigger room for the bottom left one, I will more often than not be stuck in a wall, because they are not aligned. Which I can also not solve with a 16x16 tile size.

Here is how it looks
https://github.com/KoBeWi/Metroidvania-System/assets/2575407/d3b2cda7-f1dc-41bc-ad1d-9ba9ae9d24bd
Here again with an invisible ramp of 8px
https://github.com/KoBeWi/Metroidvania-System/assets/2575407/0c921fbc-0e5e-4d12-923c-0f7754b6279d

**Comment by KoBeWi** [comment]
I managed to reproduce the issue, I should probably mention it in the README. I never tested uneven room sizes and didn't think it can be an issue.

You can avoid hard-coding rooms by tweaking the teleport code:
```GDScript
if prev_map:
	player.position.y -= floorf(player.position.y / MetSys.settings.in_game_cell_size.y) * 16 # change 16 to match your game
	player.position -= MetSys.get_current_room_instance().get_room_position_offset(prev_map)
	player.position.y += floorf(player.position.y / MetSys.settings.in_game_cell_size.y) * 16
	player.on_enter()
```
This works only for horizontal connections, you'd need to detect horizontal vs vertical for a complete solution.

**Comment by nyrrrr** [comment]
you're a life-saver!

**Comment by KoBeWi** [comment]
I looked into this issue again and the fix I provided does not work for all cases. The fractional tile offset can be any value, including irrational numbers. Thus there is no generic solution based only on teleporting the character.

However today I added a feature I had in plans, which is neighboring room previews (WIP):

![image](https://github.com/KoBeWi/Metroidvania-System/assets/2223172/6aa35415-e63a-489e-83d3-bf599b5e43a0)

In your case the misalignment can be something like this:

![image](https://github.com/KoBeWi/Metroidvania-System/assets/2223172/85fe3664-8ac4-4b41-99e9-80e919488a13)

I did not really test how feasible is that, but the "ultimate" solution for such problems is simply... offsetting the tilemap. You can craft any kind of alignment if your TileMap is not necessarily at (0, 0). The previews make that much easier to achieve. I only wonder how it fares in complex layouts with multiple potentially misaligned rooms.
