### ISSUE TITLE
Feature request: rearranging rooms in Room Layout mode

### ISSUE THREAD

**Issue by jcandres** [KoBeWi/Metroidvania-System#20]
I find that editing cells can be cumbersome, and I find myself losing a lot of time re-creating portions of the map as my levels grow. It would be very helpful if the layout editor allowed to drag-and-drop rooms around the map preserving their linked scene, symbols and other elements. But even just the ability to rearrange merged cells as a group would be wonderful.

I imagine this could work by holding alt or shift while in Room Layout mode. Ideally dropping a room would only be allowed if all the new cells are empty, to avoid losing any data.

Thanks for creating this awesome plugin!

**Comment by KoBeWi** [comment]
Added in 1bea7152ef0bdf19b950a06be931b629d3bf7edd

https://github.com/KoBeWi/Metroidvania-System/assets/2223172/d809ca67-6c8f-47b4-b255-3d89fcfbab86
