### ISSUE TITLE
Where is the settings_file and how do I modify it?

### ISSUE THREAD

**Issue by altinaaaaaaa** [KoBeWi/Metroidvania-System#21]
I just downloaded version 1.1 and I can't understand how to start it. The README says this

>After adding the plugin and enabling it, a file called `MetSysSettings.tres` will appear in your project. It contains settings for the plugin. You can move it to any directory, but you should modify `addons/metroidvania_system/settings_file` to point to the new path. Next thing to do is edit the settings file and customize all the fields (see [here](https://github.com/KoBeWi/Metroidvania-System#general-settings) for more info). The most important one is `map_root_folder`, which defines where will your map scenes go. This is also the location of your `MapData.txt` file, which stores the world layout.

The problem is that in `MetSysSettings.tres` there is nothing called `addons/metroidvania_system/settings_file`. It only has options for `Theme`, `Map Root Fodler`, `In Game Cell Size`, and `Custom Element Script`. There is nothing in the Godot Project Settings or the Godot Editor Settings referencing `addons/metroidvania_system/settings_file`. There is nothing in project directory either. The folder `res://addons/MetroidvaniaSystem/` contains nothing that is named `settings_file`. 

I don't know how to start using this plugin. I don't know what the `settings_file` is supposed to be or how to modify the path to it.

**Comment by KoBeWi** [comment]
`addons/metroidvania_system/settings_file` refers to a project setting. I updated the README, sorry for the confusion.
