### ISSUE TITLE
Sample project renders cells seemingly in the wrong position.

### ISSUE THREAD

**Issue by swissdude15** [KoBeWi/Metroidvania-System#24]
I have obtained and installed the addon regularly from the AssetLib. After I adjusted the settings of the sample project, the project was compiled without errors. The game starts with the StartingPoint scene, the player can be moved normally up to the exits.
The minimap also shows the change of the cell, but at the level borders the adjacent room does not appear as expected or the room appears in the wrong position, so that it is not possible to move across and the player falls down.

GD 4.2.1. / MetSys 1.1
Win 11

https://github.com/KoBeWi/Metroidvania-System/assets/134631577/23c1f12e-19fa-41fe-88d2-6587b96e1567

https://github.com/KoBeWi/Metroidvania-System/assets/134631577/964687cd-f0e8-40d4-860b-8e5317c0ee9b

![image](https://github.com/KoBeWi/Metroidvania-System/assets/134631577/e04a3edd-ff84-40cf-a627-60632bcd1b1f)

**Comment by KoBeWi** [comment]
Looks like your settings are misconfigured. If you want to play the sample project, you need to use its `project.godot` and the `Settings.tres` file in Resources folder

**Comment by swissdude15** [comment]
I have adjusted the path in "Resources/Settings.tres". But I have just noticed that the cell size is different. MetSysSettings.tres shows a cell size of 1152x648. 

![image](https://github.com/KoBeWi/Metroidvania-System/assets/134631577/cbe0433c-a1ed-475d-bfaa-54e548d98da7)

**Comment by KoBeWi** [comment]
Make sure `addons/metroidvania_system/settings_file` points to the correct file.

**Comment by swissdude15** [comment]
That was exactly it, the window size was different, which is why MetSysSettings.tres contained different values. 
Now, it works fine. Thank you very much! :-)

**Comment by KoBeWi** [comment]
Maybe I should mention it in the README. You are not really supposed to launch the example project from AssetLib download, because it causes problems like this.

**Comment by KoBeWi** [comment]
I have rewritten the Getting Started section in 8db49190145fb7e68e699e9205d0914e27713443. It has a paragraph about runnin the sample project.
