### ISSUE TITLE
MetSys restart failed on basically clean project

### ISSUE THREAD

**Issue by nyrrrr** [KoBeWi/Metroidvania-System#26]
I just went to the asset store and downloaded the latest version into my barebone project, which consists of nothing but a Player with FSM and a tilemap.

I am using Godot 4.2.1 and I do not see how I can have naming conflicts.

![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/135018fe-2b28-4a9d-b328-8f50cd9e8c49)
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/75e130ad-914b-463f-9f62-0181674ea339)

**Comment by KoBeWi** [comment]
What errors appear in MetroidvaniaSystem.gd?

**Comment by nyrrrr** [comment]
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2575407/33884207-9584-42c0-ba87-22de7063e07f)

When I try to set the checkmark in the Project Settings > Plugins tab, it will automatically close the IDE, reopen it and show the error popup from my original post.

**Comment by KoBeWi** [comment]
I just tried installing in an empty project and it works after restart. I excluded the SampleProject though.
Try removing .godot folder maybe.

**Comment by KoBeWi** [comment]
So it was unrelated to MetSys.
When you install or create an addon, the addons folder is created automatically. It's better to use that than to create it yourself.
