### ISSUE TITLE
Clicking the previews to navigate to connected scenes doesn't do anything

### ISSUE THREAD

**Issue by callofdutybg** [KoBeWi/Metroidvania-System#27]
In the description it says: "Godot Editor integration > You can click the previews to navigate to connected scenes." I'm selecting the RoomInstance node but cant interact with the preview. In the description gif the preview border is yellow when hovered and can open the scene by clicking. This is not happening with me, tested in Godot 4.2 and 4.2.1

**Comment by KoBeWi** [comment]
Do you see any errors in the output?

**Comment by callofdutybg** [comment]
No, nothing

**Comment by KoBeWi** [comment]
Can you post some screenshots of your map and editor? There is not enough details to tell what's wrong.

**Comment by callofdutybg** [comment]
Sure, its just the default sample project:
![project](https://github.com/KoBeWi/Metroidvania-System/assets/93443532/ee2e8996-c567-4f9b-b3f5-d218051c6bb0)

**Comment by KoBeWi** [comment]
There is a second plugin, which seems to have problems activating on first launch. Go to Project Settings -> Plugins and restart MetSys, it should be working afterwards.

**Comment by callofdutybg** [comment]
That worked, thanks!
