### ISSUE TITLE
Any docs page planned?

### ISSUE THREAD

**Issue by Visnicio** [KoBeWi/Metroidvania-System#28]
I feel that this add-on has a lot of potential, but it lacks a good and more non-linear docs than just the README.

If you guys do not have anyone working on the documentation, I would be pleased to be the first one to take that seat :)

**Comment by KoBeWi** [comment]
The README has headers, so you can use table of contents to navigate.
I remember someone on Reddit mentioned a wiki (it's a GitHub feature). Maybe I'll look into that.

**Comment by KoBeWi** [comment]
The documentation is available in Godot itself. It's generated from the GDScript files using the built-in documentation system.

**Comment by KoBeWi** [comment]
I'm in the process of moving the README to wiki: https://github.com/KoBeWi/Metroidvania-System/wiki
Once I finish, I will remove the duplicate content from README and close this issue. You can give some feedback in the meantime (and afterwards).

**Comment by Visnicio** [comment]
The docs seems pretty fine so far, congrats!

What I would add is a API reference with simples methods explanation, nohing fancy, just pure function calls and explanations, i.e:

``````
MetSys class
MetSys.get_current_room_instance()

**Comment by Visnicio** [comment]
The docs seems pretty fine so far, congrats!

What I would add is a API reference with simples methods explanation, nohing fancy, just pure function calls and explanations, i.e:

```gdscript
MetSys class

var metsys : MetSys = MetSys.new() # Instantiates/Initialize a new MetSys

MetSys.get_current_room_instance() # Returns the current map scene
```

**Comment by Visnicio** [comment]
I was thinking of forking the repo and creating a fanmade docs, and if you like it, maybe you can incorporate on the current docs

**Comment by KoBeWi** [comment]
Well as I said before, the documentation is already available inside the editor:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2223172/14be6276-2db5-4918-abc4-ddf4ee86453f)
It's briefly mentioned in the README, but maybe I should make it more prominent and list available classes. I don't know any tool that would turn GDScript documentation into something you can put on GitHub, and I'm not doing it manually, so the class docs won't be available on the wiki.

**Comment by Visnicio** [comment]
fair enough, maybe I'm just dumb, couldn't find the docs inside Godot

**Comment by KoBeWi** [comment]
Press F1 and search for MetroidvaniaSystem class.

**Comment by KoBeWi** [comment]
The wiki is finished and the documentation is mentioned here: https://github.com/KoBeWi/Metroidvania-System/wiki/General-Information#code-documentation
