### ISSUE TITLE
on running the sample with Godot 4.2 beta 1

### ISSUE THREAD

**Issue by D0NM** [KoBeWi/Metroidvania-System#3]
assertion failed
game.gd / line 233
assert(room_name in map_data.assigned_scenes)

--------------
If I run the project with Godot 4.1.2 it get in the deadly loop
- starting project
- closing the editor
- restarting
- repeat...

**Comment by KoBeWi** [comment]
As noted in the README, the project requires Godot 4.2. 4.1 is not supported.

The main script uses `Vector2i.MAX` constant, which does not exist in the older version. It causes the singleton to not load and the plugin restarts the editor, expecting the singleton to exist. Even if you fix this one error, that's not the only problem you'd face. Closing as WONTFIX.

**Comment by levlup1** [comment]
> As noted in the README, the project requires Godot 4.2. 4.1 is not supported.
> 
Where is the documentation for installing? Thanks

**Comment by KoBeWi** [comment]
Until 4.2 is stable, you can find it in the blog posts on the website or in the download archive: https://godotengine.org/download/archive/
