### ISSUE TITLE
Get variabel collectible object 

### ISSUE THREAD

**Issue by Zifai** [KoBeWi/Metroidvania-System#30]
I want to save game directory to string,
but collactible object not quefree when i am load save games,

**Comment by KoBeWi** [comment]
Seems like you might be loading the state incorrectly.
Are you using `MetSys.set_save_data()`? Does the Dictionary you use contain these items?

**Comment by Zifai** [comment]
I use this 
![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/7c508e6d-43c1-4586-b821-c44456d218ed)
and i load like this
![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/38f1ab49-04a5-46ad-948f-539ca42ac756)

**Comment by Zifai** [comment]
i not use  SAVE_PATH

**Comment by Zifai** [comment]
I us this to export to string
![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/d5e774f1-412b-4223-9e61-543c05d1cd57)
and i get data like this
![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/27711072-2557-4120-b145-6eb6b7ac3b8d)
I try to parse_string , but only player_save_point = player position
![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/414fdd2c-31d7-411a-a169-5fae8d874f65)

**Comment by Zifai** [comment]
![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/04db235d-985c-43ab-8a68-0cb6c508ef1d)

**Comment by Zifai** [comment]
I found the save game , i can call MetSys.set_save_data(save_data) to load this.
but the problem is your name variable in directory is vector3i , i don' know how to parse_string name variable  

![image](https://github.com/KoBeWi/Metroidvania-System/assets/47101454/d70394e1-751c-45cd-8c96-320c7e861432)

**Comment by KoBeWi** [comment]
Any reason why you are using JSON? If you want to save as text, you can use the function provided with MetSys (the one you screenshoted in your first reply). Or use a ConfigFile.
JSON isn't a good format for saving game data, because it doesn't support Godot custom types and integers.

**Comment by Zifai** [comment]
I managed to save collectible objects with json, unfortunately map data can only be saved in local storage, I use the Google Play Game plugin, and the data must be in string form

**Comment by KoBeWi** [comment]
You can get a String by using `var_to_str(save_manager.data)` and load it using `var data = str_to_var(loaded_string)` (remember to do `MetSys.set_save_data(data)`).

I can add some helper functions to save and load data as String. I didn't even consider it, I just assumed people would save/load from files.

**Comment by Zifai** [comment]
Great, it works thank you .

**Comment by KoBeWi** [comment]
Resolved by 44dfd30, which added new methods for saving and loading raw Strings.
