### ISSUE TITLE
Clicking previewed scene doesn't highlight or change scenes

### ISSUE THREAD

**Issue by ScreamingNarwhal** [KoBeWi/Metroidvania-System#32]
Hello! I'm working on implementing this addon and I can't seem to get the functionality of clicking the scene previews to load the adjacent scene. It doesn't highlight or have any of the expected interactions provided on the main page, any ideas what is going on?

**Comment by KoBeWi** [comment]
Same issue as https://github.com/KoBeWi/Metroidvania-System/issues/27. Try reloading the plugin.

**Comment by KoBeWi** [comment]
Fixed by 9de5ef2
