### ISSUE TITLE
Assign scene window does not work with mouse

### ISSUE THREAD

**Issue by GammaHaya** [KoBeWi/Metroidvania-System#34]
Godot 4.2.1

When you press 'Scene Assign' and click a room, a window appear.
In this window you cannot choose a scene with the mouse. You have to scroll threw the scenes with the arrow keys.
The only things that are clickable with the mouse are the three buttons 'create new scene', 'cancel' and 'Open'.

<img width="1090" alt="Bildschirmfoto 2024-01-29 um 17 04 07" src="https://github.com/KoBeWi/Metroidvania-System/assets/158074902/beee8185-de49-4879-bf9a-3f36f826b621">

**Comment by KoBeWi** [comment]
Your Create New Scene looks displaced for some reason, that's weird 🤔
Seems like some layout problem. If you don't need to use that button, you can workaround the bug by removing this node from MapEditor.tscn:
https://github.com/KoBeWi/Metroidvania-System/blob/d220de888e01284141231e85025851694946b132/addons/MetroidvaniaSystem/Database/MapEditor.tscn#L898

I will look into it later, it might be system-specific issue for some reason.

**Comment by GammaHaya** [comment]
Wow, fast reply. Thank you, your solution worked for me. I don't need that button. Now I can scroll and click the list.

I am on MacOS (Sonoma 14.1.1), if it helps

**Comment by KoBeWi** [comment]
Fixed by 196eb79
