### ISSUE TITLE
Assigning one scene to multiple cells

### ISSUE THREAD

**Issue by Darmanarnar** [KoBeWi/Metroidvania-System#41]
Is it possible to assign one scene to multiple cells? 

sorry if this is the wrong place to ask.

**Comment by KoBeWi** [comment]
It's not possible, it's mentioned in the documentation.
Why would you want to do that?

**Comment by Darmanarnar** [comment]
> It's not possible, it's mentioned in the documentation. Why would you want to do that?

sorry for the trouble, I'm making a roguelike with premade room layouts, and I want to be able to reuse the scenes for multiple rooms.

**Comment by KoBeWi** [comment]
You can use the map without assigning scenes, but you'll need to do room transitions manually. MetSys can help you with drawing.
