### ISSUE TITLE
help with map builder

### ISSUE THREAD

**Issue by Darmanarnar** [KoBeWi/Metroidvania-System#42]
trying to use the map builder. Are there any additional things I need to do to get it working with the minimap? 

![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/1b328b47-ceab-4740-9815-baf34c8e77dd)

![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/ccb8a15d-6a77-4c28-b422-3a54dad7b131)

![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/91d9b6ce-ef88-4b45-af5e-3b44d1ddd8d2)

![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/732f9333-f146-4398-86ca-cbbfbda61740)

I've got the map working without the map builder but have been struggling to get it implemented with it, any help would be greatly appreciated.

**Comment by KoBeWi** [comment]
Well creating a cell is enough to get it displayed on minimap (after you call `update_map()` once finished). What exactly doesn't work? Is it not displayed? Does the cell display wrongly?
Did you check the generator example in the sample project?

**Comment by Darmanarnar** [comment]
> Well creating a cell is enough to get it displayed on minimap (after you call `update_map()` once finished). What exactly doesn't work? Is it not displayed? Does the cell display wrongly? Did you check the generator example in the sample project?

I enabled debug for canvas items, It shows the map getting redraw signals when attempting to transition to a new room, but nothing gets updated on the map and the room doesn't change, The map just appears as blank.
![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/68251d70-39ee-4389-8fb9-2af3e6ee9ea2)


`print(map_builder.cells)` outputs 
![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/85a2901b-bfef-47fb-9dfd-a52ca009134b)

maps folder
![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/8b15231a-278f-4471-a221-f69136403cdb)

**Comment by KoBeWi** [comment]
The example is mentioned here (listing relevant scenes and scripts): https://github.com/KoBeWi/Metroidvania-System/wiki/Specific-Rooms#dice-room---procedurally-generated-rooms

> I enabled debug for canvas items, It shows the map getting redraw signals when attempting to transition to a new room, but nothing gets updated on the map and the room doesn't change,

Does this problem happen with non-generated cells? i.e. does the map transition and display correctly?

**Comment by Darmanarnar** [comment]
> The example is mentioned here (listing relevant scenes and scripts): https://github.com/KoBeWi/Metroidvania-System/wiki/Specific-Rooms#dice-room---procedurally-generated-rooms
> 
> > I enabled debug for canvas items, It shows the map getting redraw signals when attempting to transition to a new room, but nothing gets updated on the map and the room doesn't change,
> 
> Does this problem happen with non-generated cells? i.e. does the map transition and display correctly?

no, it's only a problem when using the map builder. I Also tried experimenting with the dice room in the sample project, but I couldn't figure out how to work it. 
![image](https://github.com/KoBeWi/Metroidvania-System/assets/162482546/8356f047-0beb-4b65-aac0-193ffee662de)

after touching the dice it does the animation, the door opens, but there's no transitions and I just fall when trying to exit the room.

**Comment by KoBeWi** [comment]
I fixed Dice Room in a434c20d07da06bdfc35fa627aa14908a36a82bf (it didn't have scene assigned).
It works correctly now:

https://github.com/KoBeWi/Metroidvania-System/assets/2223172/28b6b071-eb87-4271-b907-51ef3ee9a18e
