### ISSUE TITLE
MetSys not loading on export with MapData.txt intact

### ISSUE THREAD

**Issue by TheBlueRuby** [KoBeWi/Metroidvania-System#43]
When I export my project, it acts similar to #31 , however the MapData.txt file is being exported, as it exists in the PCK and my GDScript can access it. If it helps, I am using a mix of GDScript and C# in my project, and am on Godot 4.2.1.

**Comment by TheBlueRuby** [comment]
It appears as though the room_loaded signal isn't being emitted, but the room is loading.

**Comment by KoBeWi** [comment]
Do you get any errors?

**Comment by TheBlueRuby** [comment]
My scenes are referenced with UIDs, and I believe I'm using the latest version from this git repo. I do not get any errors in the console output. Other rooms are accessible via save file manipulation, so the initial load is ok. It may just be an error with signals. Also, it works completely fine when debugging from the editor or placing the editor binary in the project root.

**Comment by KoBeWi** [comment]
Ok I managed to reproduce it in the sample project. It's some problem with UIDs and only happens in exported project. I'll look into it.

**Comment by KoBeWi** [comment]
Should be resolved in 1282eb1ebbea449ee734f47c46c4b8485e89a6ff
Check if it fixes the problem for you.

**Comment by TheBlueRuby** [comment]
Works perfectly for me, thanks!
