### ISSUE TITLE
MultiMap system

### ISSUE THREAD

**Issue by DezoEsper** [KoBeWi/Metroidvania-System#44]
Can I create different separate **maps** for my project, with my own separate scene sets?

**Comment by KoBeWi** [comment]
MetSys only supports a single map data file. You could technically load another one and do a full setup again, but I'm not sure if that would work (definitely not in the editor, without lots of extra code).

But you don't really need separate maps, you can use multiple layers. Each layer has its separate rooms and you have 100% over what layer is displayed, so you could sort of have multiple maps this way. However scenes can't be assigned to multiple rooms, even on separate layer (you could work it around by using inheriting scenes if you need, they just need unique path).

**Comment by DezoEsper** [comment]
I would like to make an in-game world editor, similar to the one in Knytt Stories. :)

**Comment by KoBeWi** [comment]
Well, in the Manage tab there is an option to reload map data - you can use this code to switch maps. But the system does not support multiple map data paths. Maaaybe I could add some functions for convenient world switching, but I never considered it for the scope of the addon. I can give you some pointers if you don't know how to implement it.

**Comment by DezoEsper** [comment]
I decided a make the game without an editor for now, maybe later, if I want to add it, that would be great :) Anyway, thanks for reply!

**Comment by KoBeWi** [comment]
In c13d67f5f0e4d7560e6afb3cc59da74699ea5147 I added `load_map_data()`, which allows loading a different map directory.
