### ISSUE TITLE
Map data file does not exist

### ISSUE THREAD

**Issue by wangwangwang-cmyk** [KoBeWi/Metroidvania-System#45]
I followed the documentation to set the path for the MapRootFolder, and under this path, there is a corresponding MapData.txt file. However, after exporting the project and running the project from the console, I get the warning "Map data file does not exist". I used a translation software to translate this, so some parts may not be accurately expressed. Please excuse any inaccuracies.
![0H_HR83WF7RNB1}RI0LOZUB](https://github.com/KoBeWi/Metroidvania-System/assets/62195183/2913a199-72a4-4aca-941a-fb1a536ac253)
![9GZ`AT2){J OM I}@EHBIA2](https://github.com/KoBeWi/Metroidvania-System/assets/62195183/58374aac-8bce-4f55-86d7-690292fd6c7f)

**Comment by KoBeWi** [comment]
Did you add `*.txt` to include filters in export preset?
