### ISSUE TITLE
Issue with room name not in assigned scenes (sample project)

### ISSUE THREAD

**Issue by XanderDesai** [KoBeWi/Metroidvania-System#48]
Hey there!
I'm starting out with a fresh clone of this repo and trying to run the sample project.

Immediately upon running the program I'm getting an assertion error here https://github.com/KoBeWi/Metroidvania-System/blob/master/addons/MetroidvaniaSystem/Scripts/MapData.gd#L488

The error is that my room name `:cv55nv1c2sbiq` is not in assigned_scenes. The assigned_scenes dictionary is mostly human readable tscn filenames. there are a couple UIDs in that dict but none of them match the one that I have in the room_name variable.

Godot version 4.2. Windows 10.
I haven't made any changes other than cloning the repo and pressing run.

**Comment by bybywudi** [comment]
I encountered the same issue as you

**Comment by KoBeWi** [comment]
I can't reproduce it. Just tried a fresh clone in Godot 4.2.2.

Maybe you have some old save file? Remove `example_save_data.sav` from user data directory if it exists.

**Comment by PotatoGuy123** [comment]
I have the same problem, with also with a fresh clone

**Comment by PotatoGuy123** [comment]
> I can't reproduce it. Just tried a fresh clone in Godot 4.2.2.
> 
> Maybe you have some old save file? Remove `example_save_data.sav` from user data directory if it exists.

I'm sorry im kind of dumb, where would i find this?

**Comment by KoBeWi** [comment]
In the top editor menu: Project -> Open User Data Folder.

**Comment by PotatoGuy123** [comment]
i've checked the whole folder, and it doesn't look like it exists in there

**Comment by KoBeWi** [comment]
I don't know then. Are you using newest Godot stable with newest version of MetSys (available from GitHub)? If the scene is not found in assigned scenes, what scenes are registered?

**Comment by PotatoGuy123** [comment]
I'm godot 4.2.2, and I am 99% sure im using the latest version of the project, as I am creating a clone through using the github desktop. As for the registered scenes, I used a print statement right above the assert and this was the output

![image_2024-04-23_144644583](https://github.com/KoBeWi/Metroidvania-System/assets/94653107/b963bfda-2c14-46f5-9b9c-c84eb1ff9f1c)

**Comment by KoBeWi** [comment]
Can you provide stack trace for the error call? Your room name does not exist in the map data, I don't know where it came from.

**Comment by PotatoGuy123** [comment]
I hope this is what your looking for, im still relatively new to Godot, so please let me know if it was something else you needed instead

![image](https://github.com/KoBeWi/Metroidvania-System/assets/94653107/1a4290bc-1ed2-4e50-ac2a-c160b7c8fb2c)

**Comment by KoBeWi** [comment]
Ok this is the same issue as #8
Which is weird, because I fixed it 🤔 I'll look into it again. In the meantime you can try opening `MapData.txt` and converting line endings manually (your code editor/IDE should have such option, if you have one).

**Comment by PotatoGuy123** [comment]
alright, thanks
