### ISSUE TITLE
Assertion failed.

### ISSUE THREAD

**Issue by GammaHaya** [KoBeWi/Metroidvania-System#49]
I tried to create a new project with this plugin, but it is not working and I don't know what to do.
What I did:

- Download the Plugin +SampleProject.
- Activated Plugin
- Changed the Map Path in the settings to correct one
- Run the project

I got this error: **Assertion failed.**
File: MetroidvaniaSystem.gd
Line: 256

Is there a fix for it?

Tested on MacOs

**Comment by KoBeWi** [comment]
Sounds like you might be using old version. Download the newest ZIP from GitHub: https://github.com/KoBeWi/Metroidvania-System/archive/refs/heads/master.zip

**Comment by KoBeWi** [comment]
I pushed update to AssetLib. I have a big feature planned and wanted to finish it first, but there were too many important fixes in the meantime.

btw as noted in the starting guide, running sample project from AssetLib is unadvised due to `project.godot` conflicts.
