### ISSUE TITLE
Can't install at all?

### ISSUE THREAD

**Issue by willdayble** [KoBeWi/Metroidvania-System#50]
Hiya! Excited to try the addon! :)

So far I have tried cloning the repo directly from here, installing via AssetLib into a blank project, installing and restarting, etc. I get a variation of the same errors each time.

<img width="956" alt="Pasted Graphic" src="https://github.com/KoBeWi/Metroidvania-System/assets/29651/ca21d6de-fb76-4d7c-9374-76af928d4dc3">

Or...

<img width="856" alt="Pasted Graphic 1" src="https://github.com/KoBeWi/Metroidvania-System/assets/29651/cb7caa2d-3b3d-4714-a2b2-ea277bf26f31">

I am using Godot v4.2.2.stable.official [15073afe3] on OSX.

**Comment by willdayble** [comment]
If I try to run `Game.tscn` I get the following:

Line 0:Could not resolve class "res://addons/MetroidvaniaSystem/Template/Scripts/MetSysGame.gd".

<img width="973" alt="image" src="https://github.com/KoBeWi/Metroidvania-System/assets/29651/f22421f6-24fd-47aa-b828-ac489fddf7f8">

**Comment by willdayble** [comment]
In some variations of this, I get this when trying to run `Game.tscn`:

<img width="1284" alt="image" src="https://github.com/KoBeWi/Metroidvania-System/assets/29651/9e5e5006-5e76-41c8-8187-41059c387ffa">

**Comment by KoBeWi** [comment]
Can't reproduce. There are errors on first launch, but the editor automatically restarts to fix it. Did you try restarting and disabling/enabling the addon?

**Comment by Beebster-UK** [comment]
Hi,
      I think all that @willdayble is missing is setting the 'MetroidvaniaSystem\Nodes\Singleton.tscn' as 'Autoload' with the title 'MetSys'. After setting this dependency they can enable the plugin without error.

![MetroidVania](https://github.com/KoBeWi/Metroidvania-System/assets/4124668/1584caca-8640-4a7f-9e59-7b1aa372bd89)

Thanks,

Beebz

**Comment by KoBeWi** [comment]
This is weird, because the singleton should be added automatically when enabling the plugin.

**Comment by Beebster-UK** [comment]
Agreed, I can see where your plugin script adds the singleton but somehow it seems to be failing before it gets the chance to establish it.

**Comment by KoBeWi** [comment]
> In some variations of this, I get this when trying to run Game.tscn:

This error happens when you try running the sample project downloaded from AssetLib. The settings file is not loaded due to `project.godot` conflict. It's mentioned in the starting guide.

**Comment by Revenhawk** [comment]
Hi there!  Came across this addon after watching a YT video featuring it - went to install it, but am having the exact same problems as [willdayble](https://github.com/willdayble).  I've tried installing to blank projects via AssetLib and by downloading the .zip from github and extracting it to the addons folder - no luck.  Tried [Beebster-UK](https://github.com/Beebster-UK)'s suggestion, but only got more errors trying to load the singleton (missing dependency: MetroidvaniaSystem, even though I pointed it right to the .gd)

I thought maybe it had to do with me using the .NET version of Godot, but while I didn't get the myriad parsing errors upon loading with the base version of Godot, when trying to enable the addon, I still get the following:

![image](https://github.com/KoBeWi/Metroidvania-System/assets/17790401/5ee5af77-4270-44ac-8433-cc936e0dcfbd)

**Comment by HeadClot** [comment]
I am running into this as well using Godot 4.2.2 stable mono build.

**Comment by KoBeWi** [comment]
I recorded starting the project from freshly downloaded ZIP:
https://github.com/KoBeWi/Metroidvania-System/assets/2223172/a3355c43-3bdf-4be1-aa85-ecd618ead46e
As I already mentioned, errors on first launch are expected and the automatic restart fixes them. Is it any different for you?

**Comment by Revenhawk** [comment]
Ah, I guess I see what I was doing wrong - I wasn't trying to create a new project by directly importing the .zip file.  Instead, I was trying to create a new, blank project, unzipping the file myself with winrar, and simply moving the /addons/MetroidvaniaSystem folder into the blank project under the /addons folder I was making.

Creating a new project via the import method works.  I still don't think it'd work using the AssetLib method though.

Apologies if I misunderstood the wiki on how to load up the addon - excited to try it out now!

**Comment by KoBeWi** [comment]
I updated the quick start guide.

**Comment by KoBeWi** [comment]
Turns out the plugin code was at fault here too. e537bb97b99bb10242c97d69548bc563ce25d841 should fix the issue for real.
