### ISSUE TITLE
When working with a team, rooms are reset.

### ISSUE THREAD

**Issue by sumuraxxx** [KoBeWi/Metroidvania-System#52]
For some reason, someone from the team, for example, adds a new room and sends a commit, and others switch to this commit, then the entire map is reset, that is, in the map editor itself, everything seems to work, but when launching the project, the scenes are reset. and when you try to edit the scene in the presence of RoomInstance, RoomInstance is not shown in the editor itself, that is, there is RoomInstance in the node tree, but it is not in the scene editor

**Comment by KoBeWi** [comment]
When you pick external changes while editor is open, you need to use Reload nad Cleanup Map Data from Manage tab. I'll see if it can be done automatically.

**Comment by sumuraxxx** [comment]
Hello, is there an automatic solution to this problem? or a method that worked 100 percent, during development, even pressing a special button nothing happens and only by miracle, sometimes after a lot of time everything falls into place, but this is very difficult

**Comment by KoBeWi** [comment]
The Reload Map Data button should reset the map without fail. Are you saying it doesn't work sometimes? Do you know how to reliably reproduce this bug?

**Comment by sumuraxxx** [comment]
Иногда это слишком мягко сказано, по факту она не работает совсем:/
Присходит это вообще так: Запускаем игру карта не работает, ни переходы ничего нажимаем на кнопку запускаем игру вновь и никакого проку
Но как я недавно понял, по какой-то причине кнопка у меня работает, хоть и не всегда, но работает а к моих коллег, вовсе не работает
Ниже отправлю ошибки которые иногда вылезают
![IMG_20240718_202128_212](https://github.com/user-attachments/assets/e06bc2c7-29a3-48d1-9a8d-466477bc322a)

**Comment by KoBeWi** [comment]
How does the map change when it happens (i.e. what changes are you pulling from git)? Is it when you add new rooms? Modify assigned scenes?

**Comment by KoBeWi** [comment]
In 93b6a045f947d6a843af8063d9ea035aa8c8e5cb I added auto-reload function:

https://github.com/user-attachments/assets/e3642697-3606-430e-8ef6-486c010f26cd

See if it resolves your problem.

**Comment by sumuraxxx** [comment]
Now everything works flawlessly, thank you :))
