### ISSUE TITLE
Cannot enable  plugin

### ISSUE THREAD

**Issue by teamman270** [KoBeWi/Metroidvania-System#53]
I'm relatively new to Godot, so I don't know if this could be a problem on my part or not. I followed the instructions, but these errors came up in the output when I tried to enable the plugin.  I went to the script it listed, and I saw the error 
**"Identifier "MetSys" not declared in the current scope."**  on lines 106-108 and 111.

I am using the most up to date version of Godot. 

Errors:
res://addons/MetroidvaniaSystem/MetSysPlugin.gd:106 - Parse Error: Identifier "MetSys" not declared in the current scope.
  res://addons/MetroidvaniaSystem/MetSysPlugin.gd:107 - Parse Error: Identifier "MetSys" not declared in the current scope.
  res://addons/MetroidvaniaSystem/MetSysPlugin.gd:108 - Parse Error: Identifier "MetSys" not declared in the current scope.
  res://addons/MetroidvaniaSystem/MetSysPlugin.gd:111 - Parse Error: Identifier "MetSys" not declared in the current scope.
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/MetroidvaniaSystem/MetSysPlugin.gd" with error "Parse error". (User)
  core/config/project_settings.cpp:341 - Property not found: editor_plugins/enabled

![Godot help](https://github.com/KoBeWi/Metroidvania-System/assets/62864459/5ef55580-39a0-40c7-afc5-0cad297169b6)

![Help 2](https://github.com/KoBeWi/Metroidvania-System/assets/62864459/6840de29-4438-46d7-a08e-4143878af167)

**Comment by KoBeWi** [comment]
Sounds like this issue again #50
See if anything in that topic helps.

**Comment by HeadClot** [comment]
That PR seems to have fixed it for me.
