### ISSUE TITLE
How to respawn player at last SavePoint instead of room entrance?

### ISSUE THREAD

**Issue by HeiMao808** [KoBeWi/Metroidvania-System#54]
This is what I have so far under the kill() in player.

	func kill():
		print("You Died")
		var save_manager := Game.SaveManager.new()
		save_manager.load_from_text(Game.SAVE_PATH)
		Game.get_singleton().load_room(save_manager.get_value("current_room"))
		var start := Game.get_singleton().map.get_node_or_null(^"SavePoint")
		position = start.position

currently start.position just returns null, but I am able to load the previous room that had a save point. However, I'm wondering if there is a better way to go about this?

**Comment by KoBeWi** [comment]
`start` is null, because you need to await until the room is loaded.
One obvious improvement is moving the restart code to `Game.gd`, so it can be easily reused. But the general idea is correct.

**Comment by HeiMao808** [comment]
Ah, that makes more sense. I ended up just adding a value called save_position to be saved every time the player passes a save point or saves manually. 

	func save():
	        Game.get_singleton().save_position = player.position
	        Game.get_singleton().save_game()
	        Game.get_singleton().reset_map_starting_coords()
	        player.currentHealth = player.MaxHealth
	        Game.get_singleton().reload_game()

I did move the code over to Game.gd though.

	func reload_game():
		var save_manager := SaveManager.new()
		save_manager.load_from_text(SAVE_PATH)
		load_room(save_manager.get_value("current_room"))
		player.position = save_manager.get_value("save_position")

It's working as intended.

**Comment by KoBeWi** [comment]
This feature does not really fit the sample project as there is only one room where you can "die". If it's resolved on your end then closing.
