### ISSUE TITLE
Game Debugger closes immediately

### ISSUE THREAD

**Issue by kiebor81** [KoBeWi/Metroidvania-System#55]
**Scenario 1**

- create a new project 
- import through the asset library
- start the debugger 
- window opens, and closes immediately

**Scenario 2**

- clone repository
- import as project from disk
- start the debugger 
- window opens, and closes immediately

Both scenarios produce no errors nor any feedback in the console.

**Comment by KoBeWi** [comment]
engine version?

**Comment by kiebor81** [comment]
4.22

**Comment by kiebor81** [comment]
@KoBeWi you can close this now. I've found the problem was specific to my development laptop. It was an incompatibility with a global vulkan reshade configuration.
