### ISSUE TITLE
Issue - rooms do not allign 

### ISSUE THREAD

**Issue by Void-Metallurgy** [KoBeWi/Metroidvania-System#57]
Hello,
I have encountered a bug where two rooms are misalligned, see picture:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/115654386/cb293864-9735-44fa-bffe-3e3915762c6c)

This means that when the player passes rooms, they go up or down. For example,when moving from the left room to the right, the player looks like this:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/115654386/65c4b040-1ffc-45f3-816b-a5c0fa0e86e3)
(which isn't the issue but exemplifies the misallignment)

Notes:
- Both rooms use the exact same tileset
- other rooms ARE aligned properly

Things I've tried:
-  Check if the room or the tileset have position not vector zero: In both cases, there was no offset
- erase the rooms from the editor and re-make them. 
- reassign the scene to the rooms

The rooms in question appear on the map like this:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/115654386/f5060e28-6df9-4b9e-bef5-26867aef1523)

So far, nothing helped. is there anything I could do? It's a really odd bug and it messes up screen trasnitions. 

Thank you for your time!

**Comment by KoBeWi** [comment]
Sounds similar to #18
This can happen when your in-game room size is not divisible by tile size. E.g. if you use 32x32 tiles with 960x540 resolution, your room size in tiles will be 30x16.875, which causes misalignment. You can fix it by either adjusting your in-game room size (it does not need to match screen size) or by offsetting your TileMap position to manually align tiles. The adjacent room previews exist to help with that.

**Comment by Void-Metallurgy** [comment]
Wow, good catch!!! I Slightly changed room size and now it fits. Thank you for your quick and helpful answer!
(Ps: I really love the addon, it's great!)

**Comment by KoBeWi** [comment]
I added a troubleshooting page to address this: https://github.com/KoBeWi/Metroidvania-System/wiki/Troubleshooting
