### ISSUE TITLE
exporting the game

### ISSUE THREAD

**Issue by sumuraxxx** [KoBeWi/Metroidvania-System#61]
Hello! New problem: when exporting the game, the card is reset, it is important that when launching the game from the editor, everything works perfectly, the export settings are standard and what’s wrong is not clear

**Comment by KoBeWi** [comment]
Did you read the [export section of starting guide](https://github.com/KoBeWi/Metroidvania-System/wiki/Quick-Start#exporting)?
Do you get any errors in the console?
Can you show your `export_presets.cfg`?

**Comment by sumuraxxx** [comment]
Thank you, I was not careful, everything works!
