### ISSUE TITLE
Sample Project not working in Godot 4.2.2 and 4.3

### ISSUE THREAD

**Issue by PPBoxHead** [KoBeWi/Metroidvania-System#62]
The things I'm posting here are the same both in Godot 4.2.2 and 4.3 without any kind of difference on their behaviour:
First of all I've been reading the docs about the editor integration, and while it does work on the tab with MetSys and the scene preview gets drawn, the `If you select the RoomInstance node, you can interact with the previews. Clicking the preview will go to that scene, while preserving the current editor view.` doesn't work when I try to put the mouse over the drawn preview while having the RoomInstance selected

![image](https://github.com/user-attachments/assets/82bb406f-d818-4fe6-b1bd-060e62af9e57)

Also, this button is not showing aswell
![image](https://github.com/user-attachments/assets/fc5ff51c-2b51-4262-b911-20839a897c8c)

To sumarize and give context, this is the project that comes itself on this repository and I do not have any customized or so, just literally downloaded, opened it and when I tried to see those features they didn't worked.

I haven't had any code error or debug problem. Just doesn't give any error and yet when I open the RoomInstance script the editor crashes without any context

**Comment by PPBoxHead** [comment]
Was going to use it for Metroidvania Month 25, but I suppose it's gonna get delayed for a bit lol

**Comment by KoBeWi** [comment]
It works after you disable and enable the plugin.
I'll see what's wrong.

**Comment by KoBeWi** [comment]
Fixed by 9698e14c9571f71c8d78420bc03accb757924e68
