### ISSUE TITLE
RoomInstance and Godot 4.3 TileMap Changes

### ISSUE THREAD

**Issue by digitalbath94** [KoBeWi/Metroidvania-System#63]
Similar to this issue: Sample Project not working in Godot 4.2.2 and 4.3

The sample project works even with the added modern map and changing the TileMap to TileMapLayers with a Node2D as the parent.

![1st](https://github.com/user-attachments/assets/2f8be118-a1eb-4326-bfab-896a034f4068)

The issue I have is that as soon as I change the rooms, the RoomInstance stops working.
I have tried with existing maps and my own maps (with the RoomInstance in the tree) and made no difference. I even tried fresh with a clean repo downloaded yesterday.

![2nd](https://github.com/user-attachments/assets/1fdf4093-777e-44e2-96d1-12c3ba0b8e3c)

![3rd](https://github.com/user-attachments/assets/44c9a608-a1b0-4c62-919f-909f463611b3)

ps: Sorry to mix things up here but since I might open another issue because I think the TileMaps changes breaks the generateoverlays scripts  (i haven't ruled out the possibility that it could also be the problem here), but I still need to figure that one out. Until then, I make my own in Aseprite and it works fine.

I have tried disabeling and enabeling the plugin and it doesn't work for me.
I'm new to godot and it's the first time trying to change/adapt a plugin.

EDIT: I guess I was missing some borders in the map. I needed to change the border of the EM theme to make it easier to see but just changing the color should be enough if you don't want to change the theme. I'm aware it changes the actual map in game but at least a noob like me can see the borders.
I'll leave this open just in case there's an actual solution for this and for people that might have the same issue.

**Comment by digitalbath94** [comment]
Honestly, I think I just figured it out... I need to add borders on the map.

**Comment by KoBeWi** [comment]
The borders in editor have different color, depending if they are a wall or not:
![image](https://github.com/user-attachments/assets/a9d50a10-c155-41fd-99a8-d058407b0e1f)
Not sure why it's not visible in your screenshots though.

EM theme intentionally has single border style, because the passages are visible in the overlay. Maybe I'll add some clarification in the docs, if it's missing.

**Comment by digitalbath94** [comment]
Ah you're right, I didn't even notice the purple borders are not there!

However I meant the EM theme borders when you open the plugin, honestly me not seeing them is a me issue lol I changed them to bright green haha

![image](https://github.com/user-attachments/assets/d4340bbe-9c78-4b59-a6b2-3d5b8b7934b5)

![image](https://github.com/user-attachments/assets/2c746b37-da63-434a-a38b-a66c2430395d)



Thank you for your response and for this amazing plugin :)
