### ISSUE TITLE
Portals not using RoomTransitions

### ISSUE THREAD

**Issue by Ibenyourbro** [KoBeWi/Metroidvania-System#64]
I am trying to setup portals in my game to teleport the player ( Not between layers, just to different areas on same layer).

Issue I am running into is that when using the sample code

```
func _on_body_entered(body: Node2D) -> void:
	# If player entered and isn't doing an event (event in this case is entering the portal).
	if body.is_in_group(&"player") and not body.event:
		body.event = true
		body.velocity = Vector2()
		# Tween the player position into the portal.
		var tween := create_tween()
		tween.tween_property(body, ^"position", position, 0.5).set_ease(Tween.EASE_IN).set_trans(Tween.TRANS_SINE)
		await tween.finished
		# After tween finished, change the map.
		Game.get_singleton().load_room(target_map)
		# A trick to reset player's event variable when it's safe to do so (i.e. after some frames).
		get_tree().create_timer(0.2).timeout.connect(body.set.bind(&"event", false))
		# Delta vector feature again.
		Game.get_singleton().reset_map_starting_coords()
		
```

My Player when teleporting is appearing under my tileset and outside my `target_map` . I believe this is because player position stays the same with the above code, and my portal is at (1884,3335) and my destination's floor is (X,1080). So my player's position is exactly the same when going through the portal. And he falls out of bounds.

You can see this in the following output.
```
(2090.716, 3466.333) <-- Walking to portal
(2065.716, 3466.333)
(2065.575, 3466.232) <-- Sucked in to portal
(2064.841, 3465.701)
(2063.478, 3464.716)
(2062.224, 3463.81)
(2059.828, 3462.078)
(2056.822, 3459.905)
(2054.484, 3458.216)
(2050.486, 3455.326)
(2045.91, 3452.019)
(2042.546, 3449.587)
(2037.044, 3445.611)
(2031.011, 3441.251)
(2026.704, 3438.138)
(2019.834, 3433.173)
(2012.492, 3427.866)
(2007.349, 3424.149)
(1999.279, 3418.317)
(1990.81, 3412.196)
(1984.956, 3407.965)
(1975.886, 3401.409)
(1966.497, 3394.624)
(1960.077, 3389.984)
(1950.23, 3382.867)
(1940.153, 3375.584)
(1933.325, 3370.649)
(1922.943, 3363.146)
(1912.427, 3355.545)
(1905.358, 3350.437)
(1894.698, 3342.732)
(1884, 3335) <-- Teleport starts
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335) 
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3335)
(1884, 3339.167) <-- New Map loads in and my player falls
(1884, 3347.5)
(1884, 3360)
(1884, 3376.667)
(1884, 3397.5)
(1884, 3422.5)
(1884, 3451.667)
(1884, 3485)
(1884, 3522.5)
```

I figure it would be nice to have a way to decide where the player spawns when going through a portal maybe with Spawn_Points (you could argue this should be on the developer not the plugin) or have portals considered when using the `RoomTransitions` module. I think Portals are a pretty standard metroidvania function that may be worth fleshing out the built in functionality. To at the very least, when creating a portal with the sample code, making sure the player spawns inside the room the portal takes them too.

I have worked around this in my game, by having the portal room always look the same, but others may want something else.

If you feel this is not worth pursuing you can just close the issue ,since there are ways to work around it, no questions asked, thanks!  😊

P.S. If you have any better ideas of how I should be handling teleporting with the portal im all ears!

**Comment by KoBeWi** [comment]
There is another portal type in DarkStaircase.tscn, which I think does what you want (complete with a "spawn point").
