### ISSUE TITLE
Question: How do we show map viewer in-game?

### ISSUE THREAD

**Issue by dragoonreign** [KoBeWi/Metroidvania-System#65]
Amazing plug-in!

What I've done: 

- I've read instruction wiki and played the sample project but I couldn't find a way to show the map viewer in-game.

What I'm trying to do: 

- When I press a button I want to show a map in-game. Is there a way to accomplish this?

Thank you in advance!

**Comment by KoBeWi** [comment]
There is a minimap node that you can add to your scene: https://github.com/KoBeWi/Metroidvania-System/wiki/Other-Components#minimap

In a similar way, you can draw map manually using `draw_cell()` method: https://github.com/KoBeWi/Metroidvania-System/wiki/Basic-Map-Features#drawing-the-map

Sample project has an example of full game map under a button. You can use either of the both methods to draw it.

Currently I'm working on a new map system (the recently added MapView), but it's work in progress and not documented yet.

**Comment by dragoonreign** [comment]
Thank you for the quick reply!

Sorry for my lack of words. I have created my own map using the Metsys plug-ins "map editor" tab and also applied scenes. As image shown below.
![metsys](https://github.com/user-attachments/assets/246eb27a-a5c0-485e-ad42-3bc746c2585b)

In-game screen:
![metsys2](https://github.com/user-attachments/assets/6b6f467a-383c-402c-8563-a4a333ee099e)

Going back to my question, Is there a way to show the zoomed out map in game? 
Such as pressing "M" to open map like image below.
![metsys3](https://github.com/user-attachments/assets/ec84784c-3735-415a-b7c1-af928c03beb0)

Thank you again! :)

**Comment by dragoonreign** [comment]
Thank you!

It worked out perfectly!
![metsys4](https://github.com/user-attachments/assets/1ccf7a08-2920-4775-a4c7-bd049b601c5b)
