### ISSUE TITLE
Question: How to run individual room scene?

### ISSUE THREAD

**Issue by mycroftsnm** [KoBeWi/Metroidvania-System#66]
Hello, first thanks for this awesome plugin!

Im running the sample project to understand how the plugin works (also reading the docs ) and gonna try using it as a base  make my little dream game :) (Or should i learn first and then start a clean project?

So, i get that i can select a room in the MetSys tab and it will open the scene, but can i run that particular scene with F6 on the fly? 
When i try i'm getting:
`Invalid call. Nonexistent function 'is_object_stored' in base 'Nil'.`

There is a correct way to achieve what i want?

**Comment by KoBeWi** [comment]
Check the Custom Runner integration: https://github.com/KoBeWi/Metroidvania-System/wiki/Custom-Runner-Integration
It's another addon of mine.

**Comment by mycroftsnm** [comment]
Oh, i feel a bit stupid. Somehow i missed that wiki page. Thanks!
