### ISSUE TITLE
Room transition only working with sample project scenes

### ISSUE THREAD

**Issue by GianImpr** [KoBeWi/Metroidvania-System#67]
When I try to make a room transition with anything that isn't made with the project's tileset, this happens and the room is not loaded at all.

I have no idea why and what to do.
Used the sample project as base for this.

https://github.com/user-attachments/assets/c9435782-99b8-41c7-80fd-14722dabdb8a

**Comment by KoBeWi** [comment]
Do you get any errors? Are the rooms aligned properly? (based on their previews)

**Comment by GianImpr** [comment]
@KoBeWi 

I was using tilesets with different tile size and that also caused small misalignments, that was the issue.
Thanks for pointing that up, now everything works properly!!
