### ISSUE TITLE
Exquisite Map Theme is the only default one that works

### ISSUE THREAD

**Issue by ScarfKat** [KoBeWi/Metroidvania-System#68]
So I've tried this in both the sample project, and a blank project with only the addon installed. I'll go to the Map Editor, go to the Manage tab, and then click General Settings. The inspector then displays the Settings.tres file.

If I then try replacing the Theme with a different one, none of the Map Editor stuff displays correctly. I can't see any rooms or draw any new ones either. When validating the Map Theme after changing it like this, it reports that there are no errors. I've tried this with every default theme, and Exquisite is the only one that works correctly.

Here is an example of this happening in the sample project. I changed to the BS Theme and it moved all the rooms, displayed new ones, and misaligned them with the grid. If I attempt to draw or erase rooms, nothing visually changes.
![image](https://github.com/user-attachments/assets/0cfa72b6-7f70-4bad-acb4-63bfcb45800e)

Would greatly appreciate any help here. As besides this bug, I think this plugin is amazing and would love to use it.

EDIT: Oh also, I'm running on Godot 4.3. I'm not sure if that affects things but I figure it's worth mentioning.

**Comment by ScarfKat** [comment]
Ah, got it working. So if I change the theme, I then have to close and re-open the project. I'm not sure if this is intended or not, but it wasn't mentioned in the documentation and might be good to add there if it is the intended behaviour.

Anyway I'll leave this open in case this isn't intended, but feel free to close it if you'd like. Thanks for making such a cool plugin.

**Comment by KoBeWi** [comment]
It's not intended.
Which version are you using? The one on GitHub is still experimental and some features don't work correctly. Use the AssetLib version until it's updated.
