### ISSUE TITLE
Errors in console and switching themes doesn't work anymore after upgrade to 1.3.1

### ISSUE THREAD

**Issue by nyrrrr** [KoBeWi/Metroidvania-System#69]
Recently I wanted to upgrade from 1.2 to 1.3.1.

1. I deleted my `MetroidvaniaSystem` directory in my addons folder
2. downloaded the project zip from GitHub
3. extracted the `MetroidvaniaSystem` folder to addons.

When I now open my project:

- errorrs show up in console when I open (screen 1)
- same errors show up when I add a new room to the existing map everytime I do 
- if I switch the theme all my rooms are gone (screen 2)
- on the current theme (SotN) the map looks different than before. The background of the rooms is now blue, it was black/translucent before (screen 3 & 4)
- if I switch themes, click around and switch back, I get a map with mixed themes (screen 5)

Screen 1 - Errors: 
![image](https://github.com/user-attachments/assets/c1637282-5d8c-4e1b-b327-f5faff5e3e37)

Screen 2 - Switched Theme
![image](https://github.com/user-attachments/assets/83a02dc2-8ffd-4b2f-aa8c-2d0735d62fca)

Screen 3 - before:
![image](https://github.com/user-attachments/assets/f4d778f8-19ec-49b5-afd4-af6a5abab140)

Screen 4 - after:
 ![image](https://github.com/user-attachments/assets/e26ccd60-4d05-4723-833d-4dca9d099a07)

Screen 5:
![image](https://github.com/user-attachments/assets/9e66797f-b04b-4758-9773-4da25a9d9994)

Additional Notes:

- adding the sampleproject and extension directory don't change anything
- the game still runs. The Map is now blue instead of black, though and I cannot switch themes
- I haven't tried any of the new features like the new modern map

Were there any documented breaking changes from 1.2 to 1.3.1 that I missed?

**Comment by KoBeWi** [comment]
Godot version?

**Comment by KoBeWi** [comment]
Sorry I didn't notice earlier. Looks like you are using the version from GitHub. It's still experimental, get the addon from AssetLib for now.

**Comment by nyrrrr** [comment]
That seemed to fix it, thanks

**Comment by nyrrrr** [comment]
The only issue I have now is that whenever I start my game in the editor and then close it, it tries to tell me ther MapData.txt has changed.

![image](https://github.com/user-attachments/assets/334845e2-f1fe-4919-ae06-43fcb1dbf629)

Do you have any idea where this could be coming from?
