### ISSUE TITLE
Documentation on map discovering

### ISSUE THREAD

**Issue by Nordle** [KoBeWi/Metroidvania-System#73]
Hey, first of all thanks so much for this amazing tool <3 

I've been struggling the last day or so trying to understand how to interact with the cells so that they start as unmapped and become mapped once the player discovers them, could you point to any documentation or code where this is done?

Or more information on this snippet of documentation regarding changing cell states in the UI (if that's possible): https://github.com/KoBeWi/Metroidvania-System/wiki/Basic-Map-Features#discovering

For example, after loading the library and creating a map in the plugin, when I run `get_explored_ratio()` it always returns 1 (100%) and the whole map always shows in game when viewing it.

**Comment by KoBeWi** [comment]
Did you initialize save data? (`MetSys.set_save_data()`)

**Comment by Nordle** [comment]
I had not, I found what I needed from there thanks. I'm using a separate save system (https://github.com/AdamKormos/SaveMadeEasy) so with a slight tweak to persist the data from there instead, I now have the player location showing and map discover working nicely.

Thanks again for the wonderful tool 🥇
