### ISSUE TITLE
Editor constantly thinks MapData.txt has been edited and spam popup

### ISSUE THREAD

**Issue by DinoMC** [KoBeWi/Metroidvania-System#75]
Hi,

I have just started experimenting with this extension and it's been amazing.

I have one very annoying issue tho. Every time I run the project, the editor will show this popup telling me MapData.txt is newer on disk.
![image](https://github.com/user-attachments/assets/7e24978d-2b2a-4070-9cfc-76e318e0f4d9)
It also happens anytime I alt-tab, and I think there's other triggers. 
All in all, it feels like I have to close this popup every 30 seconds while working on the project.

I checked the content of MapData.txt and it doesn't change. And even in the filesystem, the "last written date" doesn't need to change for it to retrigger. I'm not sure why the editor thinks the file is being written to.

It starts happening as soon as I load the sample project, no need to change anything.

Is there a way to have the editor ignore it?

I'm on Godot 4.3 stable.

Thanks

**Comment by KoBeWi** [comment]
That's weird. It's Godot's own file popup, which should not appear for non-Resource files. Do you have some other addons in your project?

**Comment by DinoMC** [comment]
I was doing some more tests and I figured out what triggers the issue!
It happens when you have the MapData.txt opened in the script editor (even if you never edit anything). Not sure why I had it opened to begin with, but closing it solves the issue.

To reproduce, if you wanna check it out : 
- Download Metroidvania System from the asset store, extract.
- Import in Godot, open the project, let it convert to 4.3, close and reopen (needed for it to work properly, dunno if it's because of the conversion)
- Open MapData.txt
- Save project
- Alt tab and tab back to Godot, popup should appear.

**Comment by KoBeWi** [comment]
Saving the project will save the MapData file and Godot does not detect that, which I guess is what causes the dialog to pop up. I'm not sure if I can fix the dialog, but I could at least make it not save when there are no changes.

**Comment by DinoMC** [comment]
Yeah, I posted the steps in case you wanted to check it out, in my project I just closed the file so I don't have an issue anymore. :)
Thanks!
