### ISSUE TITLE
Upon enable makes Godot go through infinite bootloop

### ISSUE THREAD

**Issue by ShadowKael99** [KoBeWi/Metroidvania-System#9]
Exactly as title says. I enable the plugin and it causes my Godot to reset infinitely, and I have to shut down my computer to stop it.

**Comment by KoBeWi** [comment]
Are you using Godot 4.2?
Also if this happens, you should be able to Alt+F4 right after launch.

**Comment by Kevinmonitor** [comment]
Using 4.1.3 and the same problem happens here - on both the Steam and standalone versions.

**Comment by KoBeWi** [comment]
The plugin requires Godot 4.2.
Until stable release (which will be very soon) you can get it here: https://godotengine.org/download/archive/

**Comment by Kevinmonitor** [comment]
Yup, I checked, the plugin works normally on 4.2 RC1. I understand that it was built with 4.2 in mind and breaks with anything below, but I would also love for it to be usable in 4.1 if that's possible. 

Regardless it's very nice and I appreciate your efforts in developing it - it's exactly what I needed and I was able to get it plugging with an existing player scenes and some level scenes quickly! Hope you have a nice day!

**Comment by KoBeWi** [comment]
If you want it usable in 4.1, replace all `Vector2i.MAX` references to `Vector2i(999999, 999999)` (same with Vector3i and MIN if exists).

**Comment by Kevinmonitor** [comment]
Confirmed that this works and allows the plugin to load in 4.1.3 normally. Thank you very much!

**Comment by KoBeWi** [comment]
a60db99928513897c9bde93aef37d916138da8dd fixes infinite loop. 4.2 stable is planned to release ~~tomorrow~~ *soon*, so this is issue is no longer relevant.

Refer to the comment above if you still want to use Godot 4.1 for whatever reason.
